### ISSUE TITLE
Where to find an example

### ISSUE THREAD

**Issue by mattewpit** [nithingpth/keyboard-navigator#1]
Hi, where can I find an example of the library working?

**Comment by cp-bwg** [comment]
would be lovely.  Ever find one?

**Comment by nithingpth** [comment]
corrected example app link in readme.
[https://stackblitz.com/edit/keyboard-navigator?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/keyboard-navigator?embed=1&file=src/app/app.component.ts)
